CRYPTO_TICKERS = ["BTC-USD", "ETH-USD", "LTC-USD", "XRP-USD", "DOGE-USD"]

CRYPTO_START_DATE = "2015-09-01"
CRYPTO_LOOKBACK = 6
CRYPTO_MA_WINDOW = 6
CRYPTO_ROLLING_WINDOW = 12

CRYPTO_ASSET_LABELS = {
    "BTC-USD": "BTC",
    "ETH-USD": "ETH",
    "LTC-USD": "LTC",
    "XRP-USD": "XRP",
    "DOGE-USD": "DOGE",
}